version: "3.8"

services:
  app:
    build: .
    container_name: deen_shop_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      APP_ENV: dev

  db:
    image: postgres:16
    container_name: deen_shop_db
    restart: always
    environment:
      POSTGRES_DB: deenshop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: