<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260422112046 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE cart (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, user_id INT DEFAULT NULL, product_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BA388B7A76ED395 ON cart (user_id)');
        $this->addSql('CREATE INDEX IDX_BA388B74584665A ON cart (product_id)');
        $this->addSql('CREATE TABLE category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE order_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, price DOUBLE PRECISION NOT NULL, product_name VARCHAR(255) NOT NULL, order_id INT DEFAULT NULL, product_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_52EA1F098D9F6D38 ON order_item (order_id)');
        $this->addSql('CREATE INDEX IDX_52EA1F094584665A ON order_item (product_id)');
        $this->addSql('CREATE TABLE orders (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, total DOUBLE PRECISION NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tracking_number VARCHAR(100) DEFAULT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E52FFDEEA76ED395 ON orders (user_id)');
        $this->addSql('CREATE TABLE product (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titre VARCHAR(255) NOT NULL, description TEXT NOT NULL, prix DOUBLE PRECISION NOT NULL, stock INT NOT NULL, image VARCHAR(255) NOT NULL, nouveaute BOOLEAN NOT NULL, promotion BOOLEAN NOT NULL, best_seller BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, category_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D34A04AD12469DE2 ON product (category_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, nom VARCHAR(100) NOT NULL, prenom VARCHAR(100) NOT NULL, telephone VARCHAR(20) NOT NULL, adresse VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE cart ADD CONSTRAINT FK_BA388B7A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE cart ADD CONSTRAINT FK_BA388B74584665A FOREIGN KEY (product_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE order_item ADD CONSTRAINT FK_52EA1F098D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id)');
        $this->addSql('ALTER TABLE order_item ADD CONSTRAINT FK_52EA1F094584665A FOREIGN KEY (product_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEEA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD12469DE2 FOREIGN KEY (category_id) REFERENCES category (id)');
        $this->addSql('ALTER TABLE article DROP CONSTRAINT fkqnmbf0yfa804hxcw8c9gneb0v');
        $this->addSql('ALTER TABLE commande_articles DROP CONSTRAINT fkpadk79akt249p0k457au3poj6');
        $this->addSql('ALTER TABLE commande_articles DROP CONSTRAINT fktfdwft2lut05aiin013ig3cne');
        $this->addSql('ALTER TABLE panier_articles DROP CONSTRAINT fk7gbnkjky4b1vc3fdoiek2mkt1');
        $this->addSql('ALTER TABLE panier_articles DROP CONSTRAINT fknu1xjot1gg5j850063d32w68q');
        $this->addSql('ALTER TABLE panier_item DROP CONSTRAINT fkefyhmjjm3qd6opt83hxfvdarr');
        $this->addSql('ALTER TABLE panier_items DROP CONSTRAINT fki6cr0jqy8qb6f608p9sd1xmp9');
        $this->addSql('ALTER TABLE panier_items DROP CONSTRAINT fk4wo7gkp5wni8csgaw8yvpkcqb');
        $this->addSql('DROP TABLE article');
        $this->addSql('DROP TABLE categorie');
        $this->addSql('DROP TABLE commande');
        $this->addSql('DROP TABLE commande_articles');
        $this->addSql('DROP TABLE panier');
        $this->addSql('DROP TABLE panier_articles');
        $this->addSql('DROP TABLE panier_item');
        $this->addSql('DROP TABLE panier_items');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE article (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, best_seller BOOLEAN NOT NULL, description VARCHAR(255) DEFAULT NULL, image VARCHAR(255) DEFAULT NULL, nouveaute BOOLEAN NOT NULL, prix DOUBLE PRECISION NOT NULL, promotion BOOLEAN NOT NULL, stock INT NOT NULL, titre VARCHAR(255) DEFAULT NULL, categorie_id BIGINT DEFAULT NULL, image_url VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_23A0E66BCF5E72D ON article (categorie_id)');
        $this->addSql('CREATE TABLE categorie (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE commande (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_commande DATE DEFAULT NULL, total DOUBLE PRECISION NOT NULL, user_id BIGINT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE commande_articles (commande_id BIGINT NOT NULL, articles_id BIGINT NOT NULL)');
        $this->addSql('CREATE INDEX IDX_69FD29F21EBAF6CC ON commande_articles (articles_id)');
        $this->addSql('CREATE INDEX IDX_69FD29F282EA2E54 ON commande_articles (commande_id)');
        $this->addSql('CREATE TABLE panier (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id BIGINT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uk767pcfa8di7lj52dlo5f2gs5p ON panier (user_id)');
        $this->addSql('CREATE TABLE panier_articles (panier_id BIGINT NOT NULL, articles_id BIGINT NOT NULL)');
        $this->addSql('CREATE UNIQUE INDEX uk64w7r1yx3jjbj45qnj7snbqdm ON panier_articles (articles_id)');
        $this->addSql('CREATE INDEX IDX_2598381AF77D927C ON panier_articles (panier_id)');
        $this->addSql('CREATE TABLE panier_item (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, prix_unitaire DOUBLE PRECISION NOT NULL, quantity INT NOT NULL, article_id BIGINT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EBFD00677294869C ON panier_item (article_id)');
        $this->addSql('CREATE TABLE panier_items (panier_id BIGINT NOT NULL, items_id BIGINT NOT NULL)');
        $this->addSql('CREATE UNIQUE INDEX ukadu2svvhk4qivh7ovh09q5no7 ON panier_items (items_id)');
        $this->addSql('CREATE INDEX IDX_C833C6F0F77D927C ON panier_items (panier_id)');
        $this->addSql('ALTER TABLE article ADD CONSTRAINT fkqnmbf0yfa804hxcw8c9gneb0v FOREIGN KEY (categorie_id) REFERENCES categorie (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE commande_articles ADD CONSTRAINT fkpadk79akt249p0k457au3poj6 FOREIGN KEY (articles_id) REFERENCES article (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE commande_articles ADD CONSTRAINT fktfdwft2lut05aiin013ig3cne FOREIGN KEY (commande_id) REFERENCES commande (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE panier_articles ADD CONSTRAINT fk7gbnkjky4b1vc3fdoiek2mkt1 FOREIGN KEY (panier_id) REFERENCES panier (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE panier_articles ADD CONSTRAINT fknu1xjot1gg5j850063d32w68q FOREIGN KEY (articles_id) REFERENCES article (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE panier_item ADD CONSTRAINT fkefyhmjjm3qd6opt83hxfvdarr FOREIGN KEY (article_id) REFERENCES article (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE panier_items ADD CONSTRAINT fki6cr0jqy8qb6f608p9sd1xmp9 FOREIGN KEY (items_id) REFERENCES panier_item (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE panier_items ADD CONSTRAINT fk4wo7gkp5wni8csgaw8yvpkcqb FOREIGN KEY (panier_id) REFERENCES panier (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cart DROP CONSTRAINT FK_BA388B7A76ED395');
        $this->addSql('ALTER TABLE cart DROP CONSTRAINT FK_BA388B74584665A');
        $this->addSql('ALTER TABLE order_item DROP CONSTRAINT FK_52EA1F098D9F6D38');
        $this->addSql('ALTER TABLE order_item DROP CONSTRAINT FK_52EA1F094584665A');
        $this->addSql('ALTER TABLE orders DROP CONSTRAINT FK_E52FFDEEA76ED395');
        $this->addSql('ALTER TABLE product DROP CONSTRAINT FK_D34A04AD12469DE2');
        $this->addSql('DROP TABLE cart');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE order_item');
        $this->addSql('DROP TABLE orders');
        $this->addSql('DROP TABLE product');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
